export const PICS = [
  {
    path: '/travel/amsterdam.JPG',
    title: 'Amsterdam, Netherlands',
    time: 'October 2019',
    text: '',
  },
  {
    path: '/travel/austin.png',
    title: 'University of Texas at Austin',
    time: 'November 2021',
    text: '',
  },
  {
    path: '/travel/berlin.JPG',
    title: 'Berlin, Germany',
    time: 'October 2019',
    text: '',
  },
  {
    path: '/travel/best.JPG',
    title: 'Killarney National Park, Ireland',
    time: 'February 2019',
    text: '',
  },
  {
    path: '/travel/burger.JPG',
    title: 'Skopje, Macedonia',
    time: 'October 2019',
    text: 'Not a taco, but a delicious burger nonetheless',
  },
  {
    path: '/travel/cliffs.JPG',
    title: 'Cliffs of Moher, Ireland',
    time: 'February 2019',
    text: '',
  },
  {
    path: '/travel/dc.png',
    title: 'Lincoln Memorial, Washington, DC',
    time: 'February 2021',
    text: '',
  },
  {
    path: '/travel/giannina.jpg',
    title: 'Ioannina, Greece',
    time: 'June 2022',
    text: '',
  },
  {
    path: '/travel/lefkada.jpg',
    title: 'Porto Katsiki Beach, Lefkada, Greece',
    time: 'July 2021',
    text: '',
  },
  {
    path: '/travel/lobster.jpg',
    title: 'Bar Harbor, Maine',
    time: 'September 2020',
    text: '',
  },
  {
    path: '/travel/rocky.png',
    title: 'Rocky Statue, Philadelphia, Pennsylvania',
    time: 'February 2020',
    text: '',
  },
  {
    path: '/travel/soccer.JPG',
    title: 'Mochengladbach, Germany',
    time: 'October 2019',
    text: 'Live Soccer Game! Borussia Monchengladbach v. FC Augsburg',
  },
  {
    path: '/travel/lake.jpg',
    title: 'Just outside of Ioannina, Greece',
    time: 'June 2022',
    text: '',
  },
  {
    path: '/travel/dublin.JPG',
    title: 'Dublin, Ireland',
    time: 'Feb 2019',
    text: '',
  },
  {
    path: '/travel/USVI.jpg',
    title: 'St. Thomas, U.S. Virgin Islands',
    time: 'November 2023',
    text: '',
  },
  {
    path: '/travel/stone.JPG',
    title: 'Salisbury, U.K.',
    time: 'May 2018',
    text: 'Selfie at Stonehenge',
  },
];
